#!/usr/bin/env python3
# Author @ Kartikeya Mishra

from dataclasses import dataclass
from constants import CONSTANT
import sys 

@dataclass
class Utility:
    @staticmethod
    def getCoordinatesInWorldFrame(coord):
        x = y = 0
        if len(coord) > 2:
            x, y, _ = coord
        elif len(coord) == 2:
            x, y = coord
            
        y = CONSTANT.ORIGIN_POINT_OFFSET - y
        return (round(x), round(y))
    
    @staticmethod
    def actionInDegree(thetha, d_thetha = 0):
        result = thetha + d_thetha
        if result > 360:
            result = result - 360
        elif result < 0:
            result = 360 + result
        
        return result

    @classmethod
    def run_spinning_cursor(self): 

        def spinning_cursor():
            while True:
                for cursor in '|/-\\':
                    yield cursor

        self.spinner = spinning_cursor()
        sys.stdout.write(next(self.spinner))
        sys.stdout.flush()
        sys.stdout.write('\b')
     
